version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: resumedb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - resume-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume-backend
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/resumedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MISTRAL_API_KEY: ekzUMNgB4MNNH1MuPWyLHGUKSESWRXch
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - resume-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - resume-net

volumes:
  mysql-data:

networks:
  resume-net:
    driver: bridge
